[package]
name = "grove-cli"
version = "0.1.6"
edition = "2021"
description = "Git worktree manager"
license = "MIT"
repository = "https://github.com/xuzhu-591/grove"

[[bin]]
name = "grove"
path = "src/main.rs"

[dependencies]
grove-core = { path = "../grove-core", version = "0.1.6" }
clap = { version = "4", features = ["derive"] }
inquire = "0.7"
console = "0.15"
anyhow = "1"

[dev-dependencies]
tempfile = "3"
